### ISSUE TITLE
Upgarde to django 1.10

### ISSUE THREAD

**Issue by motatoes** [ImportantCool/gogonzo#21]
Currently using 1.8

https://docs.djangoproject.com/en/1.10/howto/upgrade-version/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182570446423420/182573863979169)

**Comment by motatoes** [comment]
waiting until i finish the tests for all apps to do make sure nothing breaks

**Comment by AustinGMackell** [comment]
Should I be doing something or not doing something about this?
