### ISSUE TITLE
Can't add artefacts

### ISSUE THREAD

**Issue by AustinGMackell** [ImportantCool/gogonzo#9]
Can't add my artefacts to my story. Also, even if this was working, in the long run a single drop down menu for all the artefacts in the system is going to be very problematic. 
<img width="2560" alt="screen shot 2016-07-03 at 5 22 35 pm" src="https://cloud.githubusercontent.com/assets/15120520/16547968/6af4be88-4144-11e6-882f-01f8cb38d311.png">

**Comment by motatoes** [comment]
This is a bug multi-artefact association works in the add-story page, will fix
